always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
whitespace_in_kwargs = true
remove_extra_newlines = true
short_to_long_function_def = true
always_use_return = true
align_assignment = true
align_matrix = true
align_pair_arrow = true
align_struct_field = true
align_conditional = true
conditional_to_if = true
format_docstrings = false
format_markdown = false
indent = 4
margin = 100
normalize_line_endings = "unix"
separate_kwargs_with_semicolon = true
verbose = true
